name: neoboutique
base: core20
summary: Welcome screen for Ubuntu MATE
description: |
  A welcome screen for Ubuntu MATE that provides links to helpful resources, 
  utilities and a selection of software packages.
confinement: strict
version: git
grade: devel

apps:
  neoboutique:
    command: usr/bin/launcher.sh
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages 
      LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      QT_DEBUG_PLUGINS: 0
    plugs:
      - home
      - removable-media
      - desktop
      - desktop-legacy
      - opengl
      - x11
      - wayland
      - network
      - network-bind

parts:
  neoboutique:
    source: .
    plugin: python
    stage-packages:
      - python3-pyqt5
      - python3-qtawesome

  launcher:
    source: files/
    plugin: dump
    after:
      - neoboutique


#parts:
#  sources:
#    source: src/
#    plugin: dump
#    organize:
#      '*': src/

#  assets:
#    source: assets/
#    plugin: dump
#    organize:
#      '*': assets/
#    after:
#      - sources

#  currated-apps:
#    source: software-boutique-curated-apps/dist/
#    plugin: dump
#    organize:
#      '*.json': software-boutique-curated-apps/dist/
#    after:
#      - assets

#  wrapper:
#    source: files/
#    plugin: dump
#    after:
#      - currated-apps

#  packages:
#    plugin: nil
#    stage-packages:
#      - python3-pyqt5
#      - python3-qtawesome
#    after:
#      - wrapper

layout:
  /usr/bin/platforms:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins/platforms
